# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/storage/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "D:\\argus\\argus-src\\src-tauri\\migrations"

# diesel migration run

#Commands:
#migration     一组用于生成、运行和恢复迁移的命令。
#setup         创建迁移目录，创建 DATABASE_URL 中指定的数据库，并运行现有迁移。
#database      一组用于设置和重置数据库的命令。
#completions   为diesel命令生成shell完成脚本。
#print-schema  打印数据库模式的表定义。
#help          打印此消息或给定子命令的帮助
#
#Options:
#--database-url <DATABASE_URL>
#Specifies the database URL to connect to. Falls back to the DATABASE_URL environment variable if unspecified.
#
#--config-file <CONFIG_FILE>
#The location of the configuration file to use. Falls back to the `DIESEL_CONFIG_FILE` environment variable if unspecified. Defaults to `diesel.toml` in your project root. See diesel.rs/guides/configuring-diesel-cli for documentation on this file.
#
#--locked-schema
#When `print_schema.file` is specified in your config file, this flag will cause Diesel CLI to error if any command would result in changes to that file. It is recommended that you use this flag when running migrations in CI or production.
#
#-h, --help
#Print help (see a summary with '-h')
#
#-V, --version
#Print version
#
#You can also run `diesel SUBCOMMAND -h` to get more information about that subcommand.
